### ISSUE TITLE
Adding Dual-Extruder support

### ISSUE THREAD

**Issue by MohrJonas** [thebelin/pro-purge#1]
I really appreciate your project. Do you think it would be possible to add support for a second extruder that would be purged as well?
Cheers.

**Comment by thebelin** [comment]
Hello, I have moved to a different slicer and am using klipper these days, so I haven't made many updates to pro-purge. 

It's possible to do this update, but represents a bit of work.

Do you have an example of a plugin that has settings for multiple extruders? An example would make it much easier to build support for.

**Comment by thebelin** [comment]
Dual Extruder Support added to master in commit 7960697e4c4a6d38744e2c39b730410af722b759 by NastyGamer
